#!/bin/sh
#
# @name Winghead - Custom Tandem Tilt-Wing 8 Motor
#
# @type Winghead
# @class VTOL
#
# @maintainer John Doe
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default MAV_TYPE 21
param set-default VT_TYPE 1

# Control Allocator Airframe - VTOL Tiltrotor
param set-default CA_AIRFRAME 3

############################################################################
# ROTORS
############################################################################

param set-default CA_ROTOR_COUNT 8

# M1: Front-Left-Outer (CCW)
param set-default CA_ROTOR0_PX  0.459
param set-default CA_ROTOR0_PY -0.714
param set-default CA_ROTOR0_PZ  0.0
param set-default CA_ROTOR0_KM  0.05
param set-default CA_ROTOR0_TILT 1

# M2: Front-Left-Inner (CW)
param set-default CA_ROTOR1_PX  0.459
param set-default CA_ROTOR1_PY -0.414
param set-default CA_ROTOR1_PZ  0.0
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR1_TILT 1

# M3: Front-Right-Inner (CCW)
param set-default CA_ROTOR2_PX  0.459
param set-default CA_ROTOR2_PY  0.414
param set-default CA_ROTOR2_PZ  0.0
param set-default CA_ROTOR2_KM  0.05
param set-default CA_ROTOR2_TILT 1

# M4: Front-Right-Outer (CW)
param set-default CA_ROTOR3_PX  0.459
param set-default CA_ROTOR3_PY  0.714
param set-default CA_ROTOR3_PZ  0.0
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR3_TILT 1

# M5: Rear-Left-Outer (CW)
param set-default CA_ROTOR4_PX -0.550
param set-default CA_ROTOR4_PY -0.856
param set-default CA_ROTOR4_PZ  0.0
param set-default CA_ROTOR4_KM -0.05
param set-default CA_ROTOR4_TILT 2

# M6: Rear-Left-Inner (CCW)
param set-default CA_ROTOR5_PX -0.550
param set-default CA_ROTOR5_PY -0.486
param set-default CA_ROTOR5_PZ  0.0
param set-default CA_ROTOR5_KM  0.05
param set-default CA_ROTOR5_TILT 2

# M7: Rear-Right-Outer (CW)
param set-default CA_ROTOR6_PX -0.550
param set-default CA_ROTOR6_PY  0.856
param set-default CA_ROTOR6_PZ  0.0
param set-default CA_ROTOR6_KM -0.05
param set-default CA_ROTOR6_TILT 2

# M8: Rear-Right-Inner (CCW)
param set-default CA_ROTOR7_PX -0.550
param set-default CA_ROTOR7_PY  0.486
param set-default CA_ROTOR7_PZ  0.0
param set-default CA_ROTOR7_KM  0.05
param set-default CA_ROTOR7_TILT 2

############################################################################
# TILT SERVOS
############################################################################

param set-default CA_SV_TL_COUNT 2

############################################################################
# CONTROL SURFACES
############################################################################

param set-default CA_SV_CS_COUNT 4

param set-default CA_SV_CS0_TYPE 5
param set-default CA_SV_CS1_TYPE 6
param set-default CA_SV_CS2_TYPE 5
param set-default CA_SV_CS3_TYPE 6

############################################################################
# CONTROL SURFACE EFFECTIVENESS
############################################################################

# Roll
param set-default CA_SV_CS0_TRQ_R  0.5
param set-default CA_SV_CS1_TRQ_R -0.5
param set-default CA_SV_CS2_TRQ_R  0.5
param set-default CA_SV_CS3_TRQ_R -0.5

# Pitch (rear surfaces negative for tandem configuration)
param set-default CA_SV_CS0_TRQ_P  0.5
param set-default CA_SV_CS1_TRQ_P  0.5
param set-default CA_SV_CS2_TRQ_P -0.5
param set-default CA_SV_CS3_TRQ_P -0.5

# Yaw
param set-default CA_SV_CS0_TRQ_Y  0.0
param set-default CA_SV_CS1_TRQ_Y  0.0
param set-default CA_SV_CS2_TRQ_Y  0.0
param set-default CA_SV_CS3_TRQ_Y  0.0
